In [8]:
import pandas as pd

In [9]:
pd.__version__

'3.0.2'

In [19]:
df = pd.read_excel(r'C:\Users\gkhob\Downloads\1st, 2nd - Pandas\1st, 2nd - Pandas\Country GDP Analysis- project\data.xlsx')

In [20]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [22]:
len(df) # always gives rows

195

In [23]:
df.shape # always gives diamentions(rows and columns)

(195, 5)

In [25]:
df.columns # it will display the columns names

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='str')

In [27]:
len(df.columns)

5

In [28]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [29]:
df.isna()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [30]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    str
 1   CountryCode    195 non-null    str
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    str
dtypes: float64(2), str(3)
memory usage: 12.9 KB

In [32]:
type(df)

pandas.DataFrame

In [33]:
id(df)

2933758252160

In [34]:
df.dtypes

CountryName          str
CountryCode          str
BirthRate        float64
InternetUsers    float64
IncomeGroup          str
dtype: object

In [36]:
df.head() # system bydefault print top 5 rows

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [37]:
 df.tail() # bottom  5 rows

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [39]:
df.head(10)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
1,Afghanistan,AFG,35.253,5.9000,Low income
2,Angola,AGO,45.985,19.1000,Upper middle income
3,Albania,ALB,12.877,57.2000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0000,High income
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income

# indexing and slicing in pandas

In [40]:
df[:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [42]:
df[:5]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [43]:
df[5:10]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income

In [44]:
df[3:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
6,Armenia,ARM,13.308,41.9,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [45]:
df[0:200:25]

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0         Aruba         ABW     10.244      78.900000          High income
25     Barbados         BRB     12.188      73.000000          High income
50      Ecuador         ECU     21.070      40.353684  Upper middle income
75     Honduras         HND     21.593      17.800000  Lower middle income
100       Libya         LBY     21.425      16.500000  Upper middle income
125     Namibia         NAM     29.937      13.900000  Upper middle income
150       Sudan         SDN     33.477      22.700000  Lower middle income
175     Tunisia         TUN     19.800      43.800000  Upper middle income

In [46]:
df[0:201:25]

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0         Aruba         ABW     10.244      78.900000          High income
25     Barbados         BRB     12.188      73.000000          High income
50      Ecuador         ECU     21.070      40.353684  Upper middle income
75     Honduras         HND     21.593      17.800000  Lower middle income
100       Libya         LBY     21.425      16.500000  Upper middle income
125     Namibia         NAM     29.937      13.900000  Upper middle income
150       Sudan         SDN     33.477      22.700000  Lower middle income
175     Tunisia         TUN     19.800      43.800000  Upper middle income

In [49]:
df[::10]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0          Aruba         ABW     10.244      78.900000          High income
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
20       Belarus         BLR     12.500      54.170000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
40    Costa Rica         CRI     15.022      45.960000  Upper middle income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
60         Gabon         GAB     30.555       9.200000  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
80         India         IND     20.291      15.100000  Lower middle income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
100        Libya         LBY     21.425      16.500000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
120   Mozambique         MOZ     39.705       5.400000           Low income
130  Netherlands         NLD     10.200      93.956400          High income
140       Poland         POL      9.600      62.849200          High income
150        Sudan         SDN     33.477      22.700000  Lower middle income
160     Suriname         SUR     18.455      37.400000  Upper middle income
170   Tajikistan         TJK     30.792      16.000000  Lower middle income
180      Uruguay         URY     14.374      57.690000          High income
190  Yemen, Rep.         YEM     32.947      20.000000  Lower middle income

In [51]:
df[::-50]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5000,Low income
144,French Polynesia,PYF,16.393,56.8000,High income
94,Kiribati,KIR,29.044,11.5000,Lower middle income
44,Czech Republic,CZE,10.200,74.1104,High income